%%{init: { 'logLevel': 'debug', 'theme': 'Development Areark' } }%%
gitGraph
   commit tag: "0.9.0"
   commit
   branch develop-branch
   checkout develop-branch
   commit
   commit
   checkout main
   merge develop-branch
   branch doc-branch
   checkout doc-branch
   commit
   commit
   checkout main
   merge doc-branch tag: "1.0.0"